### PR TITLE
Custom corner radius on desktop widgets

### PR DESCRIPTION
**Pull request by Pkshields**
Hello!

This PR adds an option to change the corner radius for widgets on the desktop.

In the Desktop settings, a new "Widget corner radius" configuration option has been added. This allows the user to change the corner radius of the widget to anything between 0dp and 24dp. The default corner radius for widgets is still the same as it is in the base branch, 16dp.

[[Image] Widget corner radius setting](https://user-images.githubusercontent.com/49100076/186272003-c9a45e07-428a-4b59-803e-d635425f2056.png)
[[Image] Widgets with a 5dp corner radius](https://user-images.githubusercontent.com/49100076/186272059-83231de2-3787-4036-a594-12541e0e7e21.png)
[[Image] Resize widget box matches the custom widget radius](https://user-images.githubusercontent.com/49100076/186272101-a5f102cc-7046-4e0c-b5b1-6a1d16fa4500.png)

Would resolve [feature request ticket 231](https://github.com/NeoApplications/Neo-Launcher/issues/231).

Thanks!

### CODE REVIEW

**Review by saulhdev — COMMENTED** [review]
Would you please remove the preference from preferences_desktop.xml?
We are not longer adding any new preference to the xml files. All the new features will be on the Compose preferences only.

**Comment by saulhdev** [comment]
Did you test the code on an emulator or device?
It doesn't work on my devices so I might revert the changes.

**Comment by Pkshields** [comment]
I tested this on both a simulator and my physical Pixel 5. 

I did try adding the configuration option to just the compose preferences, however it wasn't showing up in the desktop config view for me, which is why I added it to the XML as well. In what way is it not working for you?

**Comment by Pkshields** [comment]
Sounds good. Let me know if I can help in any way!

**Comment by Pkshields** [comment]
Hi,

I looked into this a bit this evening. There is an issue with this PR, primarily caused by the wrong number of steps being configured on the new widget radius. The correct preference entry should be this...

```
    var desktopWidgetRadius = DimensionPref(
        key = PREFS_WIDGET_RADIUS,
        titleId = R.string.title_desktop_widget_corner_radius,
        defaultValue = 16f,
        maxValue = 24f,
        minValue = 0f,
        steps = 23,
        specialOutputs = { "${it.roundToInt()}dp" },
        onChange = recreate
    )
```

I am happy to submit a second PR to rectify this if you would like?

Separately, there is second issue. While the default is configured here as `16f`, it appears in the preference page as `44dp`. I believe this is related to the `dpToPx`/`pxToDp` conversations that take place in `DimensionPref`. I haven't found the solution to that yet since it is outside the scope of this PR, but since I noticed this I wanted to flag it up to you.

**Comment by saulhdev** [comment]
go ahead and create a new PR.
I tried the XML preference and does not work.
you can try the compose pref in Settings > Developer Options > New Preferences

**Pull request merged**
